# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinfo',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
