# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 07:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbinfo', '0002_auto_20170831_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
